### ISSUE TITLE
StorageClass support

### ISSUE THREAD

**Issue by dudo** [dudo/turing-pi#10]
Investigate solutions for persistent storage within the Kubernetes cluster.

Front runners include
- longhorn (there seems to be claims of it consuming too much CPU)
- openEBS
- some other CSI driver??

Since we have NVMe drives connected to the nodes, we should focus on solutions that can utilize them.

**Comment by dudo** [comment]
longhorn is the frontrunner still.

**Comment by dudo** [comment]
Went with local storage for now

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/homebridge
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - jetson1
```
