### ISSUE TITLE
Flux webhook Receiver

### ISSUE THREAD

**Issue by dudo** [dudo/turing-pi#7]
Set up https://fluxcd.io/flux/guides/webhook-receivers/

Their example uses Ingress. Let's use [Gateway API](https://gateway-api.sigs.k8s.io/guides/#install-the-crds). Something like 

```yaml
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: example-gatewayclass
spec:
  controller: <ingress-controller-name>

---
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: example-gateway
  namespace: flux-system
spec:
  gatewayClassName: example-gatewayclass
  listeners:
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          gateway: example-gateway
      namespaces:
        from: "Same"

---
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: webhook-receiver-route
  namespace: flux-system
  labels:
    gateway: example-gateway
spec:
  hostnames:
  - flux-webhook.example.com
  rules:
  - matches:
    - path:
        type: Prefix
        value: /
    forwardTo:
    - serviceName: webhook-receiver
      port: 80
```

Since this is a home server... couple things need to happen first. Here's a [decent article](https://itnext.io/securely-ingressing-into-bare-metal-kubernetes-clusters-with-gateway-api-and-tailscale-cc68299b646a) capturing the high level requirements. I don't think we need tailscale or duckdns, though (and might not even need metallb, since were using Gateway API?). Let's plan on using https://dudo.dev to route to the cluster.

- [ ] Grab a static IP from my ISP
- [ ] Open up 443 on the modem/router firewall
- [ ] Install cert-manager
- [ ] cilium can be used as a GatewayClass controller?? https://gateway-api.sigs.k8s.io/implementations/#cilium
